### ISSUE TITLE
How to add animation to my logo?? 

### ISSUE THREAD

**Issue by rmControls** [jonbhanson/flutter_native_splash#123]
Hi,

first of all Congrats and Thanks for developing a great package..... 

how to add basic animations like zoomIn/Out for logo??

**Comment by awarmfastbear** [comment]
I'd also like to know if it's possible to add animations. Maybe basic gif support or webm support?

**Comment by Shiba-Kar** [comment]
same here

**Comment by jonbhanson** [comment]
I am not sure if it is practical to implement this feature, since it would have to be done in each native platform.

The native splash screen is displayed while the native app loads the Flutter framework.  On a modern device, this should be pretty fast. Once Flutter loads, there may still be resources that need to be loaded before your app is ready. For this reason, you should consider implementing a Flutter splash screen that is displayed while these resources load. This second splash screen would be a good place to use your animation, and all of Flutter's graphics power would be available at that point.

Here is a code example of a secondary Flutter splash screen, or use a package from [pub.dev](https://pub.dev).

```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
      future: Future.delayed(Duration(seconds: 3)),
      builder: (context, AsyncSnapshot snapshot) {
        // Show splash screen while waiting for app resources to load:
        if (snapshot.connectionState == ConnectionState.waiting) {
          return MaterialApp(home: Splash());
        } else {
          // Loading is done, return the app:
          return MaterialApp(
            home: Scaffold(body: Center(child: Text('App loaded'))),
          );
        }
      },
    );
  }
}

class Splash extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Icon(
          Icons.apartment_outlined,
          size: MediaQuery.of(context).size.width * 0.785,
        ),
      ),
    );
  }
}
```

**Comment by jonbhanson** [comment]
My perspective on this feature is that it would be a feature that cannot really be fully utilized since the splash screen should be displayed quickly since it is only displayed while the flutter framework is loaded.  Better to implement animation on a subsequent secondary splash screen.  Feel free to voice your opinion if you disagree.

**Comment by rmControls** [comment]
May be I am not correct or talking nonsense... but my opinion is that why do we need to have two flash screen before and after of flutter framework load....? I just wanted to keep native flash screen until it loads its db, services and decides the next screen...

**Comment by jonbhanson** [comment]
_"I just wanted to keep native flash screen until flutter framework loads its db, services and decides the next screen..."_

These activities are done after the native splash screen has completed, so if you still want to have a splash screen to appear during these activities, it requires a second splash screen.

**Comment by jonbhanson** [comment]
In order to find out what file formats are most needed by the community, I have opened a single ticket to capture all image format requests.  Please visit (this ticket)[https://github.com/jonbhanson/flutter_native_splash/issues/245] to vote for the image format you need.
