### ISSUE TITLE
can we add delay in splash screen ?

### ISSUE THREAD

**Issue by adnankhan74444** [jonbhanson/flutter_native_splash#152]

**Comment by jonbhanson** [comment]
# FAQs
## Can I change the duration of the splash screen?
The native splash screen is displayed while the native app loads the Flutter framework. Because the resources in your app cannot load while the native splash screen is displayed, the native splash screen must be as fast as possible.  However, if you want a longer splash screen, see the secondary splash screen recommendation.


For more information, check out the readme.
