### ISSUE TITLE
Launch screen is not working in iOS

### ISSUE THREAD

**Issue by MaheshPeri19** [jonbhanson/flutter_native_splash#174]
I am getting below error when i run flutter pub run flutter_native_splash:create
It is working perfectly in Android, but not working in iOS.

```
Not able to find "LaunchImage" in LaunchScreen.storyboard. Image for splash screen not updated. Did you modify your default LaunchScreen.storyboard file?
pub finished with exit code 1
```

**Comment by jonbhanson** [comment]
The package expects to find the storyboard as it is in a new default Flutter app.  It appears that your LaunchScreen.storyboard has been modified, which is preventing the package from updating it.  You could try creating a new flutter app and copying the default LaunchScreen.storyboard over to your existing project and then running the package.  Or, post your LaunchScreen.storyboard here and I can take a look at it.

**Comment by MaheshPeri19** [comment]
Thanks for your reply. I created new flutter app and installed this package. Works well. But white screen is appearing one second in between, before splash screen. how to solve white screeen issue ?

**Comment by jonbhanson** [comment]
On iOS, it is necessary to uninstall your app, powering off your device, power back on, and then reinstall to fix the cached white screen problem.
[Reference](https://stackoverflow.com/questions/33002829/ios-keeping-old-launch-screen-and-app-icon-after-update)

**Comment by MaheshPeri19** [comment]
Thank you. Solved it. Now working perfectly.

**Comment by jonbhanson** [comment]
This issue is related to iOS caching the splash screen on your local device.  If it is the first time uploading to the App Store, this glitch could not happen.  I guess that if you have a splash screen in an app published to the App Store and you change the splash screen in a subsequent version uploaded to the App Store, you could have users with the first splash screen cached on their local device that is momentarily displayed when loading the updated version of the app.  However, this is just a guess.

**Comment by MaheshPeri19** [comment]
Okay. Thank you.
