### ISSUE TITLE
Android 12 new default splash screen duplication

### ISSUE THREAD

**Issue by ProstoSanja** [jonbhanson/flutter_native_splash#175]
**Describe the bug**
Android 12 introduced a new splash screen for all apps, that is shown until something like first draw (web terminology, sorry) happens. It looks quite different to the splash that is created in this app. [Developer docs API link](https://developer.android.com/about/versions/12/features/splash-screen). Probably something needs to be done in order to streamline the switch between 2 options that we have. Like making them look the same to not see the switch or finding a way to disable one of the implementations. No clue what is easier, as haven't looked into implementation options of this new api yet.

**To Reproduce**
1. Install android 12 beta
2. Open app that uses flutter_native_splash

**Expected behavior**
No visual indication that 2 different splash screens are shown.

**Screenshots**
https://user-images.githubusercontent.com/26527928/119554629-93b07280-bda5-11eb-98e6-e7d3a9f115c8.mp4

**Device (please complete the following information):**
 - Device: Pixel 5
 - OS: Android 12 Beta 1

**Flutter doctor**
Irrelevant

**Comment by jonbhanson** [comment]
I will push out an update soon to add beta support for Android 12:

Android 12 has a [new method](https://developer.android.com/about/versions/12/features/splash-screen) of building splash screens, which consists of specifying the window background, animated app icon, and the icon background.  Android 12 also supports legacy splash screens as they have been implemented in Flutter and this package.  At this time, this package will provide beta support for Android 12 with a legacy implementation.  By adding a `styles.xml` in `values-v31` and `values-night-v31` folders, Android 12 maintains the legacy splash screen.

The package will add support for the new Android 12 splash screens in the future.  However, I will wait to see how Flutter adapts to the new splash screen format so that this package can complement Flutter's implementation and avoid reinventing the wheel.
