### ISSUE TITLE
Image Entrance Animation

### ISSUE THREAD

**Issue by LucaDillenburg** [jonbhanson/flutter_native_splash#222]
Some options for the image's entrance animation would be great (such as zoom).
Thanks for your hard working and efforts!

**Comment by jonbhanson** [comment]
The best way to accomplish this would be with image support such as gif or lottie. In order to find out what file formats are most needed by the community, I have opened a single ticket to capture all image format requests.  Please visit (this ticket)[https://github.com/jonbhanson/flutter_native_splash/issues/245] to vote for the image format you need.
