### ISSUE TITLE
support fit image as splash

### ISSUE THREAD

**Issue by renanyoy** [jonbhanson/flutter_native_splash#24]
on iOS native development I usually use a single square image that  fit (cropped) the device screen, like this one. as this it works on every device in every orientation
![splash](https://user-images.githubusercontent.com/259671/66589231-5c6c5e00-eb8e-11e9-9642-6982f32d95d7.png)

**Comment by renanyoy** [comment]
or like this one
![splash](https://user-images.githubusercontent.com/259671/66589504-f7653800-eb8e-11e9-8b1d-50c80fc78c30.png)

**Comment by henriquearthur** [comment]
Do you mean the image should take all screen size?

There is a `fill` option you can use for that but it only works for Android at the moment.

From README:
> In case your image should use all available screen (width and height) you can use fill property.
> 
> ```yaml
> flutter_native_splash:
>   image: assets/images/splash.png
>   color: "42a5f5"
>   fill: true
> ```
> Note: fill property is not yet implemented for iOS splash screens.

The problem is that doesn't work for iOS. I am not an iOS developer and I depend on a Mac OS virtual machine + iOS Simulator running on Ubuntu to test this package and that's why I haven't digged into it yet.

**Comment by renanyoy** [comment]
fill the area and keeping the aspect ratio (I call it fit cropped)

**Comment by jonbhanson** [comment]
Commit 9a8b7ce allows the configuration of every Android gravity and iOS ContentMode option.
