### ISSUE TITLE
Support of .webp background images

### ISSUE THREAD

**Issue by AlexandreMarkus** [jonbhanson/flutter_native_splash#244]
**Is your feature request related to a problem? Please describe.**
I would like the splash screen to support webp format (image.webp)

**Comment by jonbhanson** [comment]
Thanks for your image format support request.  In order to find out what file formats are most needed by the community, I have opened a single ticket to capture all image format requests.  Please visit (this ticket)[https://github.com/jonbhanson/flutter_native_splash/issues/245] to vote for the image format you need.
