### ISSUE TITLE
Theme based on the app theme

### ISSUE THREAD

**Issue by ricardodalarme** [jonbhanson/flutter_native_splash#327]
**Describe the solution you'd like**

The splash theme is currently based on the phone theme, but it would be nice if it was based on the app's own theme, as the app may have a different theme than the phone's theme

**Comment by jonbhanson** [comment]
@ricardodalarme are you referring to the light/dark mode setting?

**Comment by ricardodalarme** [comment]
@jonbhanson exactly

**Comment by jonbhanson** [comment]
This package creates a splash screen that is displayed before Flutter is loaded.  Because of this, when the splash screen loads, internal app settings are not available to the splash screen.  Unfortunately, this means that it is impossible to control light/dark settings of the splash from app settings.
