### ISSUE TITLE
Support gif

### ISSUE THREAD

**Issue by dvorapa** [jonbhanson/flutter_native_splash#33]

**Comment by jonbhanson** [comment]
I am not sure if it is practical to implement this feature, since it would have to be done in each native platform.

The native splash screen is displayed while the native app loads the Flutter framework.  On a modern device, this should be pretty fast. Once Flutter loads, there may still be resources that need to be loaded before your app is ready. For this reason, you should consider implementing a Flutter splash screen that is displayed while these resources load. This second splash screen would be a good place to use your animation, and all of Flutter's graphics power would be available at that point.

Here is a code example of a secondary Flutter splash screen, or use a package from [pub.dev](https://pub.dev).

```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
      future: Future.delayed(Duration(seconds: 3)),
      builder: (context, AsyncSnapshot snapshot) {
        // Show splash screen while waiting for app resources to load:
        if (snapshot.connectionState == ConnectionState.waiting) {
          return MaterialApp(home: Splash());
        } else {
          // Loading is done, return the app:
          return MaterialApp(
            home: Scaffold(body: Center(child: Text('App loaded'))),
          );
        }
      },
    );
  }
}

class Splash extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Icon(
          Icons.apartment_outlined,
          size: MediaQuery.of(context).size.width * 0.785,
        ),
      ),
    );
  }
}
```

**Comment by jonbhanson** [comment]
However, it would be better to use a different file format for an animation since [GIFs are discouraged](https://developer.android.com/guide/topics/graphics/drawables) in Android.

**Comment by jonbhanson** [comment]
In order to find out what file formats are most needed by the community, I have opened a single ticket to capture all image format requests.  Please visit (this ticket)[https://github.com/jonbhanson/flutter_native_splash/issues/245] to vote for the image format you need.

**Comment by dvorapa** [comment]
Weirdly enough this stage (loading Flutter framework) is the slowest when starting the app, once Flutter is loaded, reading user's files and loading additional stuff is much quicker. Anyway, I no longer need gif in my project, but I love the idea of having one general issue and vote for the suggestions there.
