### ISSUE TITLE
Flash Screen in flavors works only in dark mode 

### ISSUE THREAD

**Issue by youssefmaly** [jonbhanson/flutter_native_splash#426]
**Describe the bug**

**To Reproduce**
1.  My yaml is as simple as  
```
flutter_native_splash:
  color: "#8BAEF8"
  image: assets/splash-prod.png
```
3. Native Splash Screen only appears on the dark mode. 
4. In the normal mode it is just a blank white screen. 

**Device (please complete the following information):**
 - Device: MIUI 
 - OS: Android 12 

**Flutter doctor**
Please paste the results of the `flutter doctor -v` here
flutter doctor 
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.4, on Microsoft Windows [Version 10.0.22621.521], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.12)
[√] Android Studio (version 2021.2)
[√] IntelliJ IDEA Ultimate Edition (version 2022.1)
[√] VS Code (version 1.71.0)
[√] Connected device (4 available)
[√] HTTP Host Availability

**Additional context**

**Comment by jonbhanson** [comment]
There is a section of the configuration that is specific to Android 12, because Google change the splash behavior for Android 12.  Your splash screen will not work in Android 12 until you have configured this section.  Please read the [notes in the readme](https://pub.dev/packages/flutter_native_splash#android-12-support) on Android 12.

**Comment by jonbhanson** [comment]
Feel free to reopen if you are still having trouble.
