### ISSUE TITLE
[Question] Image invalid in light mode.

### ISSUE THREAD

**Issue by Lelouch-cc** [jonbhanson/flutter_native_splash#447]
When I set up the Splash page, it works in dark mode, but not in light mode.
The reason is that the plugin does not add 
> \<item name="android:windowBackground">@drawable/launch_background\</item>

to styles.xml under values-31, this is a bug, please fix it.

![iShot_2022-11-04_10 19 00](https://user-images.githubusercontent.com/31361764/199871053-0704a4aa-0f0f-4fe0-8ae6-5e663876b1f3.png)

OS: Android 12

**Comment by Lelouch-cc** [comment]
My config

![iShot_2022-11-04_10 22 24](https://user-images.githubusercontent.com/31361764/199871557-083c2b53-69e7-4086-8465-af7bcc834d73.png)

**Comment by jonbhanson** [comment]
There is a bug that I will fix in the next release, but it is actually not the bug you are reporting.

For Android 12 there is a specific section `android_12` of the config file for setting Android 12 settings.  Since you don't have an `android_12` section, your `values-31` shouldn't be changed.

Your problem should be solved by adding an `android_12` section.

I will add a fix so that the `values-31` will not be modified if there is no `android_12` config.
