### ISSUE TITLE
The screen will be black for one second on IOS platform

### ISSUE THREAD

**Issue by sirawatGG** [jonbhanson/flutter_native_splash#477]
This issue came from [463](https://github.com/jonbhanson/flutter_native_splash/issues/463)
Using preserve and remove causing a black screen at app's launch.
The FlutterNativeSplash appears, then a black screen, then the first screen of the app.

**Library version**
 - dart - sdk: ">=2.18.0 <3.0.0"
 - flutterSdkVersion": "3.3.7
 - ib-version flutter_native_splash: ^2.2.16

**Device (please complete the following information):**
 - Device: iPad Mini 2
 - OS: 12.5.6

**Comment by jonbhanson** [comment]
I am not able to reproduce.  When I run the example app on iOS simulator, there is no black screen between the splash and the app screen.  Please advise how to reproduce.

Is it possible that your app is still loading resources, causing the screen not to render?  You could test for this scenario by replacing your main function with a very basic app that just loads a scaffold and blank color.  If the black screen goes away, you would know it's due to slow load.

**Comment by assanbayev** [comment]
i have the same problem on any ios. even if i add preserve and remove the black screen appears and if i never use remove after using preserve the screen will be black forever

**Comment by jonbhanson** [comment]
@assanbayev it would be most helpful in diagnosing this problem if you could send me a code sample which reproduces this problem.

**Comment by assanbayev** [comment]
@jonbhanson my main function is async. so it takes several seconds till runApp function starts. even if I just put await Future.delayed(Duration(seconds:2)) before run app it shows black screen. am I doing something wrong?

**Comment by jonbhanson** [comment]
I was able to reproduce with your feedback @mrqaidi, thanks!

Here is the code that I used that produced a black screen on load:
```dart
Future<void> main() async {
  WidgetsBinding widgetsBinding = WidgetsFlutterBinding.ensureInitialized();
  FlutterNativeSplash.preserve(widgetsBinding: widgetsBinding);
  FlutterNativeSplash.remove();
  await Future.delayed(const Duration(milliseconds: 3000), () {});
  runApp(const MyApp());
}
```
The reason this code produces a black screen is because the splash screen is removed with the `FlutterNativeSplash.remove()` command before the app is ready to be built.  In this case, the reason the app is not ready to be built is because if the `await Future.delayed`, but in another app the same effect could be caused by waiting for resources to load, waiting for a server response, etc.  For this reason, it is important to remove the splash screen only when the screen is ready to be built.  The example app in this package shows a good way to implement this.  For the simplistic example above, the black screen can be removed simply by moving the `FlutterNativeSplash.remove()` after the delay to the point where the app is ready to be built:
```dart
Future<void> main() async {
  WidgetsBinding widgetsBinding = WidgetsFlutterBinding.ensureInitialized();
  FlutterNativeSplash.preserve(widgetsBinding: widgetsBinding);
  await Future.delayed(const Duration(milliseconds: 3000), () {});
  FlutterNativeSplash.remove();
  runApp(const MyApp());
}
```

**Comment by jonbhanson** [comment]
In your splash screen page, do you have any resources that take some time to load after your `initState()` runs?  For example, in your build function are you loading any images over a network connection that may take some time to load?  To test, modify your build function to just display a solid color.  Does the black screen still remain?

**Comment by jonbhanson** [comment]
Did you do the test I suggested?  Also, make sure the `FlutterNativeSplash.remove();` is at the end of your `initState()`.

**Comment by anthonyhunter** [comment]
I have had similar problem in the past, check `UILaunchStoryboardName` key is set correctly in Info.plist

```
<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
```

Also, iOS does cache splash screen which can cause issues if updated across builds. I always run my first build from Xcode after splash screen update, rather than from VS Code.

**Comment by appinteractive** [comment]
> I have had similar problem in the past, check `UILaunchStoryboardName` key is set correctly in Info.plist
> 
> ```
> <key>UILaunchStoryboardName</key>
> 	<string>LaunchScreen</string>
> ```
> 
> Also, iOS does cache splash screen which can cause issues if updated across builds. I always run my first build from Xcode after splash screen update, rather than from VS Code.

That one fixed it for me 👍

**Comment by jonbhanson** [comment]
Glad you were able to resolve this.  If anyone in this thread is still having a problem, feel free to open a new ticket.

**Comment by philipgiuliani** [comment]
In my case, XCode has set the UILaunchStoryboardName to `LaunchScreen.storyboard` which does not work. Setting it just to "LaunchScreen" resolves the issue.
