### ISSUE TITLE
splash screen not working in android 12+

### ISSUE THREAD

**Issue by nooraldin** [jonbhanson/flutter_native_splash#480]
**Describe the bug**

in new Android 12 + 12+ 
_(W/FlutterActivityAndFragmentDelegate( 8253): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.)._
**after remove this**
```
   <meta-data
                android:name="io.flutter.embedding.android.SplashScreenDrawable"
                android:resource="@drawable/launch_background"
                /> 
```
the splash screen not working for Android12 and 12+

2- and in Android 33 API *(The Flutter logo appears, and then my logo appears !!!)

 - Device: [Pixel 3 XL]
 - Android12 and 12+ (API 32+33):

**Comment by jonbhanson** [comment]
Please post your config.

**Comment by jacky70638** [comment]
The problem I'm having is after installing
There will be no startup image problem when the app is opened for the first time
But the second time it's ok

**Comment by dyardy** [comment]
I just downloaded latest from this repo, ran on pixel 4 api emulator and I see the blue but no icon.  My own app same issue, where icon is not displayed.

**Comment by jonbhanson** [comment]
Have you seen the [notes](https://pub.dev/packages/flutter_native_splash#android-12-support) on Android 12?  There are a couple cases where the image does not show which are a limitation of Android12+.  I will close this ticket because the follow up information was not provided.  If you still have a problem, feel free to reopen with the requested details.
