### ISSUE TITLE
App failed to load past the splash screen

### ISSUE THREAD

**Issue by Azim87** [jonbhanson/flutter_native_splash#486]
Review device details:

- Device type: iPhone

- OS version: iOS 16.2

Does anyone face any kind of problem with the app?

**Comment by jonbhanson** [comment]
Usually when this happens it is a problem within the app that is preventing the app from loading, but since the splash screen is what the user sees, the problem seems associated with the splash screen.  I would recommend troubleshooting the problem by setting the main function to return a basic app with a scaffold that just displays a simple widget.  In this way you can see if the app loads without trouble, showing that the splash screen is ok.
