### ISSUE TITLE
incompatible between flutter_native_splash >= 2.2.17 and flutter_launcher_icons 0.11.0

### ISSUE THREAD

**Issue by WilbertK1** [jonbhanson/flutter_native_splash#498]
I don't think it is considered as a bug, but wanted to mention it

Describe the bug
depends on both flutter_launcher_icons ^0.11.0 and flutter_native_splash ^2.2.17, version solving failed

To Reproduce
add easy_localization and easy_localization_loader

Screenshots
Because flutter_native_splash >=2.2.17 depends on image ^4.0.10 and flutter_launcher_icons 0.11.0 depends on image ^3.0.2, flutter_native_splash >=2.2.17 is incompatible with flutter_launcher_icons 0.11.0.
And because no versions of flutter_launcher_icons match >0.11.0 <0.12.0, flutter_native_splash >=2.2.17 is incompatible with flutter_launcher_icons ^0.11.0.
So, because mobile_agent depends on both flutter_launcher_icons ^0.11.0 and flutter_native_splash ^2.2.17, version solving failed.
pub get failed (1; So, because mobile_agent depends on both flutter_launcher_icons ^0.11.0 and flutter_native_splash ^2.2.17, version solving failed.)

**Comment by MxD-js** [comment]
same issue

**Comment by jonbhanson** [comment]
This error is occurring because the [image](https://pub.dev/packages/image) package recently had a major revision from version 3 to version 4. I have updated my package to use the latest version of image, but any other packages such as flutter_launcher_icons and icons_launcher which still use version 3 of image will have this error.  I suggest you open a ticket with the conflicting packages and request that they update to the current version of image.

In the meantime, you can roll back to flutter_native_splash version 2.2.16 to avoid this error.

**Comment by emre86t** [comment]
same issue
