### ISSUE TITLE
on huawei p12 pro , android splash screen display big , all other devices splash screen show perfect 

### ISSUE THREAD

**Issue by sadaqatdev** [jonbhanson/flutter_native_splash#507]
on huawei p12 pro , android splash screen display big , all other devices splash screen show perfect 

**Configuration**

Paste the flutter_native_splash section of your yaml config.

**Device (please complete the following information):**
 - huawei p12 pro
 - android 10

**Screenshots**
 
![Screenshot_20230126_173255_com rido passengerapp](https://user-images.githubusercontent.com/69109162/215084522-b2b077e3-5217-46b3-9710-42a35b2a6486.jpg)

icon used for splash 

// pub file

flutter_native_splash:
  
![appiconn](https://user-images.githubusercontent.com/69109162/215085989-59bbf491-dd10-400a-ae40-7bce0107f5cc.png)

  
  color: "#3d5361"

  image: "assets/appiconn.png"

  android_12:

    image: "assets/appiconn.png"

    
    color: "#3d5361"

**Comment by jonbhanson** [comment]
It looks like that device runs HarmonyOS 2.0, not Android. [source](https://www.gsmarena.com/huawei_matepad_pro_12_6_(2021)-10942.php) Since all other devices display correctly, I think it is safe to conclude that the problem is with HarmonyOS 2.0 not implementing the splash screen the same and Android.

**Comment by jonbhanson** [comment]
Closed due to inactivity.  Feel free to reopen if you are still having a problem.
