### ISSUE TITLE
svg/vector asset/xml support

### ISSUE THREAD

**Issue by kuqmua** [jonbhanson/flutter_native_splash#59]

**Comment by jonbhanson** [comment]
Hello, can you explain the need for vector support?

**Comment by jonbhanson** [comment]
I will close this ticket due to inactivity, but feel free to reopen with a more explanation if you like.

**Comment by tagirahmad** [comment]
> Hello, can you explain the need for vector support?

MAy be in order to have good quality of the pic?

**Comment by alvindrakes** [comment]
Any updates on svg support for this package?

**Comment by jonbhanson** [comment]
What platform(s) would you use SVG's?

**Comment by Mayb3Nots** [comment]
Hi i am looking forward to svg support for images on IOS and andriod and plans on implmenting it?

**Comment by alvindrakes** [comment]
> What platform(s) would you use SVG's?

I think the communities want something to covert chosen svg file to respective png files for splash screens automatically.

We can do it manually, but having this feature is definitely a time saver.

**Comment by VictorUvarov** [comment]
I assume they want higher-quality images by using vector images as opposed to converting an SVG to a png file.

Both platforms seem to support SVGs on the splash screens. iOS's UIImage seems to support SVGs and Android Studio allows you to convert your SVGs to an XML file to use as a drawable. 

[Android Splash screen tutorial](https://www.youtube.com/watch?v=rIHArmoq9f8)

**Comment by cmedamine** [comment]
TengHui Zhu explains why we should use Vector drawables instead of png or jepg images:
video: https://youtu.be/wlFVIIstKmA
android guide: https://developer.android.com/guide/topics/graphics/vector-drawable-resources

**Comment by jonbhanson** [comment]
Thanks for your image format support request.  In order to find out what file formats are most needed by the community, I have opened a single ticket to capture all image format requests.  Please visit (this ticket)[https://github.com/jonbhanson/flutter_native_splash/issues/245] to vote for the image format you need.

**Comment by SarahTrees** [comment]
The designers probably create the original as SVG.
If "flutter_native_splash" could make all PNG files from this SVG, as the library already does today from the PNG specified by "image", all these png would have a better quality. 

"flutter_native_splash" is a great help, thank you very much for this wonderful library, if it would now take the SVG as source instead of resizing pixel graphics, it would be perfect. This stage of development might also be faster than switching completely to svg.

**Comment by kohj1018** [comment]
flutter_native_splash is a very good library.
But I think it will be better if it supports SVG files.
Are there any plans to support SVG files?
