### ISSUE TITLE
Splash images show substantial aliasing

### ISSUE THREAD

**Issue by esDotDev** [jonbhanson/flutter_native_splash#598]
The images produced with this library show a lot of aliasing:
![image](https://github.com/jonbhanson/flutter_native_splash/assets/736973/a194aa75-8fea-4e60-bd11-e1ed47a8e2fb)

We would hope for it to look more like:
![image](https://github.com/jonbhanson/flutter_native_splash/assets/736973/d2a8c5f8-4322-4a7e-a3a9-a104d4f38cbc)

It looks like the AVERAGE mode might be better than CUBIC for down-scaling images: 
https://github.com/brendan-duncan/image/issues/23

Maybe this can be made into a config option?

**Comment by jonbhanson** [comment]
I chose `Interpolation.cubic` because in the `image` package, it is ([described as the highest quality](https://github.com/brendan-duncan/image/blob/d6c8782067d490e5ab7eb986845fa9e1ee6f75d0/lib/src/image/interpolation.dart#L9)) :

```dart
/// Cubic blend between the neighboring pixels. Slowest, highest Quality.
```

As long as the `image` package has that description, I believe this package should use the `cubic` mode.  If your image is not resized with the highest quality, I suggest that you should open a ticket with the `image` package.

**Comment by esDotDev** [comment]
Yes, but if you read the linked thread, they added AVERAGE mode specifically because cubic is quite poor when down-scaling. 

Could you expose this setting so developers can choose the mode that best makes sense for their assets?

**Comment by esDotDev** [comment]
For example, here is CUBIC (left) vs AVERAGE (right) when downscaling a large image:
![image](https://github.com/jonbhanson/flutter_native_splash/assets/736973/db146a8b-ebf8-4a4c-bdbf-64d33ca7d6db)

Zooming in on the image really shows the poor aliasing of CUBIC
![image](https://github.com/jonbhanson/flutter_native_splash/assets/736973/3fe11d08-e455-4b01-8002-b8ac2b807028)

**Comment by jonbhanson** [comment]
OK, I read through that thread more carefully and I see what you mean.  I am more inclined to just use `AVERAGE` rather than make it a developer option.  I would like to avoid option bloat, and this choice appears to have a clear winner.
