### ISSUE TITLE
Readme "Android 12+ Support" - explanation of icon background

### ISSUE THREAD

**Issue by Mercutio1243** [jonbhanson/flutter_native_splash#659]
Dear team,

for first time users as myself, I would propose to make the explanation on icon background a bit clearer, otherwise it is a bit confusing what is meant:

**Current explanation:**
> App icon without an icon background, as shown on the left: This should be 1152×1152 pixels, and fit within a circle 768 pixels in diameter.
> App icon with an icon background, as shown on the right: This should be 960×960 pixels, and fit within a circle 640 pixels in diameter.

**Proposed change:**
> In case no icon background is specified in the parameters (as shown on the left), an image of size 1152×1152 pixels should be used, where the icon fits within a circle 768 pixels in diameter.
> In case an icon background is specified in the parameters  (as shown on the right), an image of size 960×960 pixels should be used, where the icon fits within a circle 640 pixels in diameter.

Assuming this is what is meant here? Still, I am confused, why the displayed icons are of different size depending on whether an icon background color is used?

**Comment by jonbhanson** [comment]
Thank you for the feedback.  This documentation comes straight from the [Android documentation](https://developer.android.com/develop/ui/views/launch/splash-screen), so I will leave it unchanged, rather than attempting to clarify it at the risk of misinterpreting it.  I am also confused why the icons are different sizes.
