### ISSUE TITLE
dart run  run flutter_native_splash:create error!

### ISSUE THREAD

**Issue by omergunaydin** [jonbhanson/flutter_native_splash#672]
⚠️ The parameter "cupertino_icons" was found in your flutter_native_splash config, but "cupertino_icons" is not a valid flutter_native_splash parameter. How can i fix it ?

**Comment by alitalaee** [comment]
Hello i had the same Issue and it happend because of my wrong 

**Wrong pubspec.yaml**
`
flutter_native_splash:
  ios: true
  android: true
  color: "#ffffff"
  image: "assets/splash.png"
  cupertino_icons: ^1.0.2 
  webview_flutter: ^4.7.0

**cupertino_icons be a subcontent of native_splash**

`flutter_native_splash:
  ios: true
  android: true
  color: "#ffffff"
  image: "assets/splash.png"

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.


cupertino_icons: ^1.0.2
webview_flutter: ^4.7.0
flutter_launcher_icons: ^0.13.1`


I hope it will help

**Comment by jonbhanson** [comment]
Yes, @alitalaee has identified the problem.  So, in his example it would be corrected by moving `cupertino_icons` to be under the `dependencies` section instead of under the `flutter_native_splash` section.
