### ISSUE TITLE
migrate `js` to `web` package

### ISSUE THREAD

**Issue by phamconganh** [jonbhanson/flutter_native_splash#676]

**Comment by narekv7** [comment]
When attempting to integrate the `flutter_native_splash` package into the project alongside `firebase_auth`, 
 a version conflict arises due to incompatible dependencies on the `js` package. The `firebase_auth` 
 package relies on a specific version of `js` that is not compatible with the version required by 
 `flutter_native_splash`, resulting in version solving failures during dependency resolution.
 
 Logs
``` log
Because firebase_auth >=4.17.9 depends on firebase_auth_web ^5.10.0 which depends on js ^0.6.3, firebase_auth >=4.17.9 requires js ^0.6.3.
And because flutter_native_splash 2.3.13 depends on js ^0.7.1 and no versions of flutter_native_splash match >2.3.13 <3.0.0, firebase_auth >=4.17.9 is incompatible with
  flutter_native_splash ^2.3.13.
So, because flutter_app depends on both flutter_native_splash ^2.3.13 and firebase_auth ^4.17.9, version solving failed.
```

**Comment by jonbhanson** [comment]
I will push out an update shortly that removes the `js` dependency.
